### ISSUE TITLE
Support Vue 3 ?

### ISSUE THREAD

**Issue by thibaut-lo** [jbaysolutions/vue-grid-layout#439]
Is it foreseen that Vue-Grid-Layout supports incoming Vue 3 ?

With latest `vue-grid-layout 2.3.7` and `vue 3.0.0-beta.18`, we get 

![image](https://user-images.githubusercontent.com/66995824/86576657-4f439a80-bf79-11ea-86c8-05504324fb54.png)

**Comment by strxetics** [comment]
any news on this?

**Comment by onmyflow** [comment]
It seems to me that this project is abandoned. 
There hasn't been a commit since October 2019 with currently 140 issues open... Maybe someone with dedication will fork this repo and rewrite/adapt it for vue3?

**Comment by gmsa** [comment]
Its not abandoned, just been really busy.

Vue 3 is not released yet, so not a priority right now. Feel free to implement Vue 3 support and submit a PR

**Comment by onmyflow** [comment]
That's good to hear. I might find some time do submit a PR since we anyways need this library at work.

**Comment by Aljodomo** [comment]
Vue 3 was just released. Any progress on this end?

**Comment by SergeyKhval** [comment]
I managed to run this in Vue3 environment with Vite https://github.com/SergeyKhval/vue3-grid-layout. This is not production ready, just a minimal set of changes needed to run this in Vue3. I am also not sure if it is possible to support both Vue2 and Vue3 in the same codebase. @gmsa if you open a separate branch I can make a PR

**Comment by gmsa** [comment]
Thanks @SergeyKhval ! Just created the vue3 branch.

**Comment by SergeyKhval** [comment]
Opened a PR here #470

**Comment by gmsa** [comment]
Thank you, I'll give it a look when I have some time.

**Comment by manang** [comment]
Hi @SergeyKhval , I want to test your PR,
I'm trying to compile it with 
npm run-script build and I obtain this error:

`vite v1.0.0-rc.4
⠴ Building for production...
[vite] Build errored out.
Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at error (/Users/manangel/vue/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:5210:30)
    at throwPluginError (/Users/manangel/vue/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:17817:12)
    at Object.error (/Users/manangel/vue/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:18436:24)
    at Object.error (/Users/manangel/vue/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:17990:38)
    at /Users/manangel/vue/vue-grid-layout/node_modules/rollup-plugin-vue/dist/index.js:183:63
    at Array.forEach (<anonymous>)
    at Object.transform (/Users/manangel/vue/vue-grid-layout/node_modules/rollup-plugin-vue/dist/index.js:183:39) {
  id: '/Users/manangel/vue/vue-grid-layout/src/components/GridItem.vue?vue&type=style&index=0&lang.css',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'vue',
  watchFiles: [
    '/Users/manangel/vue/vue-grid-layout/index.html',
    '/Users/manangel/vue/vue-grid-layout/src/main.js',
    '/Users/manangel/vue/vue-grid-layout/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
    '/Users/manangel/vue/vue-grid-layout/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js',
    '/Users/manangel/vue/vue-grid-layout/node_modules/@vue/shared/dist/shared.esm-bundler.js',
    '/Users/manangel/vue/vue-grid-layout/src/App.vue',
    '/Users/manangel/vue/vue-grid-layout/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js',
    '/Users/manangel/vue/vue-grid-layout/src/App.vue?vue&type=script&lang.ts',
    '/Users/manangel/vue/vue-grid-layout/src/App.vue?vue&type=template&id=7ba5bd90',
    '/Users/manangel/vue/vue-grid-layout/src/components/index.js',
    '/Users/manangel/vue/vue-grid-layout/src/components/GridItem.vue',
    '/Users/manangel/vue/vue-grid-layout/src/components/GridLayout.vue',
    '/Users/manangel/vue/vue-grid-layout/src/components/GridItem.vue?vue&type=script&lang.ts',
    '/Users/manangel/vue/vue-grid-layout/src/components/GridItem.vue?vue&type=template&id=15f3b9ae',
    '/Users/manangel/vue/vue-grid-layout/src/components/GridItem.vue?vue&type=style&index=0&lang.css'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-grid-layout@2.3.9 build: `vite build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-grid-layout@2.3.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/manangel/.npm/_logs/2020-10-02T09_55_40_037Z-debug.lo`

can you tell me if I'm doing well? 
thanks

**Comment by SergeyKhval** [comment]
@manang I mentioned in PR comment that currently build is broken because I moved from webpack to vite. I am figuring out how to restore it. For now you can run it in dev mode (`yarn dev`). If you find out how to overcome this PostCSS issue feel to ping me.

**Comment by manang** [comment]
Ah, sorry,
let me check if I find out a solution.

Thanks a lot

**Comment by SergeyKhval** [comment]
@manang I downgraded `autoprefixer` and it fixed build error. However I am still not sure if built scripts would work properly. You can pull latest changes

**Comment by manang** [comment]
thanks

**Comment by jok311** [comment]
Hi @SergeyKhval, I got this error when I use it in vue3
Uncaught (in promise) TypeError: external_commonjs_vue_commonjs2_vue_root_Vue_default.a is not a constructor
    at Proxy.created

**Comment by SergeyKhval** [comment]
@jok311 this is because the package currently lacks proper build step. For now you can only run it in dev mode (`yarn dev`). You can also try to build it yourself with `yarn build` command, but I cannot guarantee that bulit package will also work as expected.

**Comment by jok311** [comment]
> @ jok311，这是因为该软件包当前缺少适当的构建步骤。目前，您只能在开发人员模式（`yarn dev`）中运行它。您也可以尝试使用`yarn build`命令自己构建它，但是我不能保证bulit包也可以按预期工作。

thanks, I have a try.

**Comment by SergeyKhval** [comment]
I pushed changes to #470 which add a working build step for Vue3 with rollup. take a note that to properly use built packages in Vue3 + Vite you need to add the following `vite.config.js`:

```javascript
export default {
    optimizeDeps: {
        include: ['vue-grid-layout']
    }
}
```

**Comment by xiaoForest** [comment]
@SergeyKhval Hello, can the above scheme support VUE3 (#^.^#)

**Comment by PilockHulmes** [comment]
@SergeyKhval Thanks! Build with `yarn build` works for me, though in order to build successfully, I need to put `vue()` to the start of `plugins` list in `rollup.config.js`, like

```js
    plugins: [
        vue(), // put it here
        nodeResolve(),
        commonjs(),
        typescript({
            tsconfig: false,
            experimentalDecorators: true,
            module: 'es2015'
        }),
        postcss({
            plugins: [require('autoprefixer')]
        }),
        terser(),
    ]
```
Found this solution in https://github.com/vuejs/rollup-plugin-vue/issues/231#issuecomment-433743131

**Comment by jok311** [comment]
any body get this error when npm run build ?


src/components/index.js → dist/vue-grid-layout.common.js, dist/vue-grid-layout.umd.min.js...
[!] (plugin commonjs) SyntaxError: Unexpected token (2:4) in /code/demo/vue-grid-layout/src/components/GridLayout.vue?vue&type=template&id=afbc0f80&lang.js
src/components/GridLayout.vue?vue&type=template&id=afbc0f80&lang.js (2:4)
1:
2:     <div ref="item" class="vue-grid-layout" :style="mergedStyle">
       ^
3:         <slot></slot>
4:         <grid-item class="vue-grid-placeholder"
SyntaxError: Unexpected token (2:4) in /code/demo/vue-grid-layout/src/components/GridLayout.vue?vue&type=template&id=afbc0f80&lang.js
    at Object.pp$4.raise (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:15573:13)
    at Object.pp.unexpected (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:13265:8)
    at Object.pp$3.parseExprAtom (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:14972:10)
    at Object.pp$3.parseExprSubscripts (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:14775:19)
    at Object.pp$3.parseMaybeUnary (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:14752:17)
    at Object.parseMaybeUnary (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:19167:29)
    at Object.pp$3.parseExprOps (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:14687:19)
    at Object.pp$3.parseMaybeConditional (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:14670:19)
    at Object.pp$3.parseMaybeAssign (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:14638:19)
    at Object.pp$3.parseExpression (/code/demo/vue-grid-layout/node_modules/rollup/dist/shared/rollup.js:14604:19)

**Comment by plc-dev** [comment]
Is there any update on the state of the migration or when this is going to be available for production usage in the official library?

I'd also be willing to help push the issue if you could give me some pointers on what steps are missing/need to be worked on @SergeyKhval / @gmsa

**Comment by SergeyKhval** [comment]
@plc-dev as for me it looks more or less ready, just need to add fix for build issue described aboe

**Comment by plc-dev** [comment]
@SergeyKhval  Thanks for the response.

I've fixed the mentioned build issues in the [vue3-branch of my fork](https://github.com/plc-dev/vue-grid-layout/tree/vue3) of the repository as described above. 
Also I had to rename the value-prop in the GridLayout component in order to retain reactivity of the layout.
This is due to these [breaking changes](https://v3.vuejs.org/guide/migration/v-model.html#v-model ) and overload of "value" in the Ref-Type I believe.
The examples seem out of date as well, since the prop.sync option was replaced by v-model.prop and v-for requires the binding of a key-property which are missing in the examples (atleast the [basic example](https://github.com/jbaysolutions/vue-grid-layout/blob/vue3/examples/01-basic.html)).

@gmsa Do you see anything still missing for an official vue-3-release? I'd also be willing to update the examples if that would help push the issue.

**Comment by plc-dev** [comment]
@gmsa Thanks for your response. 

No, only the vue-grid-layout has to be built via vite and rollup. The project importing vue-grid-layout still only requires the built files in the dist-directory. 

I think the only thing that might be an issue is if there is more synched props in other places that have name collisions, such as the mentioned value-prop in the GridLayout component, (I only briefly checked and didn't see any), but the fix for that would be trivial.

**Comment by SergeyKhval** [comment]
May be it'll be good if dev dependencies also get updated. At least Vite guys release like crazy and current version of Vite is far ahead from what is used here

**Comment by dhondtlaurens** [comment]
This doesn't apply to Vue3 projects initiated with the Vue CLI (Webpack) I guess?. I still encounter the `TypeError: external_commonjs_vue_commonjs2_vue_root_Vue_default.a is not a constructor` problem there.

**Comment by dhondtlaurens** [comment]
I could get it to work by:

1. Cloning https://github.com/plc-dev/vue-grid-layout/tree/vue3
2. Checkout to `vue3` branch
3. Build the project by first `yarn install` and then `yarn build`
4. Use the built files from the `dist` folder in my own vue3 project

@jok311 , @betterRunner, @rhlatky

  #475 #518

**Comment by MironenkoDeveloper** [comment]
> I could get it to work by:
> 
> 1. Cloning https://github.com/plc-dev/vue-grid-layout/tree/vue3
> 2. Checkout to `vue3` branch
> 3. Build the project by first `yarn install` and then `yarn build`
> 4. Use the built files from the `dist` folder in my own vue3 project
> 
> @jok311 , @betterRunner, @rhlatky
> 
> #475 #518

I try to connect this dist from this branch to my application on to the vue 3, but the grid don't work 

![Screenshot 2021-01-24 at 19 11 22](https://user-images.githubusercontent.com/35580366/105636161-04876280-5e78-11eb-8d03-8eef32d9d8fd.png)

**Comment by dhondtlaurens** [comment]
Hi @MironenkoDeveloper,

I've actually put the built files in the dist folder of the node_modules so I can use the normal way of importing the grid in the Vue project:

`import { GridLayout, GridItem } from 'vue-grid-layout/dist/vue-grid-layout.common'`

`components: {
    GridLayout,
    GridItem
  }`

If it doesn't work, here is a link to the files I've built and use:
[dist.zip](https://github.com/jbaysolutions/vue-grid-layout/files/5865217/dist.zip)

Hope this works!

**Comment by SergeyKhval** [comment]
@MironenkoDeveloper I am not sure, that this will work the way you include built files. For local dependencies you can use paths in package.json file or use `npm link` to create a symlink to local dependency.

**Comment by gmsa** [comment]
@SergeyKhval I'm trying to vite on the branch with "yarn dev" and I'm getting this error:

````
yarn run v1.22.5
$ vite
[vite] failed to load config from C:\projects\JBAY\vue-grid-layout\vite.config.js:
C:\projects\JBAY\vue-grid-layout\vite.config.js:1
export default {
^^^^^^

SyntaxError: Unexpected token export
````

Any ideas?

**Comment by fts1025** [comment]
I've forked this project to support Vue 3 for temporary use.
It should less troubles as there are minimum changes.

https://github.com/fts1025/vue-grid-layout/tree/vue3-webpack

## Install

```sh
npm i -S https://github.com/fts1025/vue-grid-layout.git#vue3-webpack
```

## Import the library

```js
import { GridItem, GridLayout } from 'vue-grid-layout'

export default {
  components: {
      GridItem,
      GridLayout,
   },
}
```
or

```js
import { createApp } from 'vue';
import App from './App.vue';
import VueGridLayout from 'vue-grid-layout'

createApp(App)
  .use(VueGridLayout)
  .mount('#app');
}
```

## Usage

rewrite prop name `layout` to `value`.

```vue
<grid-layout
  :value="layout"
  ...
>
  <grid-item
    v-for="item in layout"
    ...
  >
    {{item.i}}
  </grid-item>
</grid-layout>
```

**Comment by MironenkoDeveloper** [comment]
> I've forked this project to support Vue 3 for temporary use.
> It should less troubles as there are minimum changes.
> 
> https://github.com/fts1025/vue-grid-layout/tree/vue3-webpack
> 
> ## Install
> ```shell
> npm i -S https://github.com/fts1025/vue-grid-layout.git#vue3-webpack
> ```
> 
> ## Import the library
> ```js
> import { GridItem, GridLayout } from 'vue-grid-layout'
> 
> export default {
>   components: {
>       GridItem,
>       GridLayout,
>    },
> }
> ```
> 
> or
> 
> ```js
> import { createApp } from 'vue';
> import App from './App.vue';
> import VueGridLayout from 'vue-grid-layout'
> 
> createApp(App)
>   .use(VueGridLayout)
>   .mount('#app');
> }
> ```
> 
> ## Usage
> rewrite prop name `layout` to `value`.
> 
> ```
> <grid-layout
>   :value="layout"
>   ...
> >
>   <grid-item
>     v-for="item in layout"
>     ...
>   >
>     {{item.i}}
>   </grid-item>
> </grid-layout>
> ```

Don't help me
import { GridItem, GridLayout } from 'vue-grid-layout'

export default {
  components: {
      GridItem,
      GridLayout,
   },
}

But this help for me. Thanks
import { createApp } from 'vue';
import App from './App.vue';
import VueGridLayout from 'vue-grid-layout'

createApp(App)
  .use(VueGridLayout)
  .mount('#app');
}

**Comment by MironenkoDeveloper** [comment]
I did try use this `npm i -S https://github.com/fts1025/vue-grid-layout.git#vue3-webpack` but base events don't work =(

**Comment by gmsa** [comment]
Published a beta release for vue3 on [npm](https://www.npmjs.com/package/vue-grid-layout/v/3.0.0-beta1)

Sample using it available [here](https://github.com/jbaysolutions/vue-grid-layout-sample-v3)

There are still some bugs, like responsive layouts not working, would appreciate any help, source branch is [vue3-webpack](https://github.com/jbaysolutions/vue-grid-layout/tree/vue3-webpack)

**Comment by tbtalbottjr** [comment]
Trying out 3.0.0.beta1 in an attempt to convert my app to VueJs 3.0. I am having the same problem as above:

`import { GridLayout, GridItem } from 'vue-grid-layout'`

returns 'undefined' for GridLayout and GridItem.

While it looks like `app.use(VueGridLayout)` does work, I have a customized GridItem and need to get that definition directly and use it.

**Comment by lvjunhao** [comment]
> I did try use this `npm i -S https://github.com/fts1025/vue-grid-layout.git#vue3-webpack` but base events don't work =(

you can use it https://github.com/lvjunhao/vue-grid-layout

**Comment by lvjunhao** [comment]
try it https://github.com/lvjunhao/vue-grid-layout

**Comment by nicotu01** [comment]
Hi !
I Cannot use it in Vue 3 project. Is there an example project ?

**Comment by lvjunhao** [comment]
> Hi !
> I Cannot use it in Vue 3 project. Is there an example project ?

This is a package, put it in node_modules

**Comment by Blakeinstein** [comment]
> Published a beta release for vue3 on [npm](https://www.npmjs.com/package/vue-grid-layout/v/3.0.0-beta1)

Do events not work? There are some inconsistencies with me using [vue-preferences](https://github.com/streaver/vue-preferences/) to store the layout in local storage, and was planning on using the layout updated event to save the layout.

**Comment by rushil-saraogi** [comment]
Anything I can hack to get the responsive mode to work?

**Comment by Blakeinstein** [comment]
> Anything I can hack to get the responsive mode to work?

But responsive mode does work.
Here is what my markup looks like.
```html
<grid-layout
  v-model:layout="layout"
  :col-num="10"
  :col-size="20"
  :is-resizable="true"
  :use-css-transforms="true"
  :auto-size="false"
  :row-height="10"
  :vertical-compact="false"
  :prevent-collision="true"
  :margin="margin"
  @layout-updated="updateLayout"
  class="content-grid"
>
```

**Comment by Daenu** [comment]
I always get an error: Unhandled error during execution of mounted hook
so that navigation and other functions aren't possible after that

**Comment by hspaay** [comment]
Looks like responsive mode has a bug in it:
In GridLayout.vue:418 it only saves the current layout if it doesn't exist.
```
  if(this.lastBreakpoint != null && !this.layouts[this.lastBreakpoint])
```
If the layout already exists it is not saved and layout changes are lost.
Maybe this should simply be this?
```
  if(this.lastBreakpoint != null)
```
I don't have the setup to test this. If anyone would be able to that be great.

**Comment by hisuwh** [comment]
Is there any progress in moving this from beta to rc?

**Comment by zhoulujun** [comment]
https://github.com/zhoulujun/vue3-grid-layout

**Comment by zhoulujun** [comment]
> 

tsx版本，可以用

**Comment by 50rayn** [comment]
Try using the module [vue3-drr-grid-layout](https://www.npmjs.com/package/vue3-drr-grid-layout), mentioned in [comment](https://github.com/jbaysolutions/vue-grid-layout/issues/617#issuecomment-1239889670)

**Comment by shariquerik** [comment]
Is there any progress in moving this from beta to stable for Vue3

**Comment by fabianB30** [comment]
Hello! is there any news on the Vue3 version? Im having the same issue that brought me to this thread. The issue is: 

Uncaught TypeError: external_commonjs_vue_commonjs2_vue_root_Vue_default.a is not a constructor

**Comment by 50rayn** [comment]
@shariquerik @fabianB30 Have a try with [vue3-drr-grid-layout](https://www.npmjs.com/package/vue3-drr-grid-layout)](https://www.npmjs.com/package/vue3-drr-grid-layout) ?

**Comment by fabianB30** [comment]
@50rayn this did work! thanks for the help

**Comment by fabianB30** [comment]
@50rayn Hello! in the code included in the vue3-drr-grid-layout docs, the script tag is written without the lang="ts", but in my proyect i must include it. But when i do, the gridItemProps all break. i get this error message: 

Uncaught (in promise) TypeError: Cannot destructure property 'gridItemProps' of 'undefined' as it is undefined.

is there a workaround for this? Thanks

**Comment by 50rayn** [comment]
@fabianB30 Can you please open an issue in _vue3-drr-grid-layout_ repo and tag also the creator? I'll also try to research this issue. 

thanks in advance :)

**Comment by dhaladitya108** [comment]
hey, I am unable to make it work with nuxt 3. 

I have tried both these, but I am facing issue in the server side while refresh. 

> Published a beta release for vue3 on [npm](https://www.npmjs.com/package/vue-grid-layout/v/3.0.0-beta1)
> 
> Sample using it available [here](https://github.com/jbaysolutions/vue-grid-layout-sample-v3)
> 
> There are still some bugs, like responsive layouts not working, would appreciate any help, source branch is [vue3-webpack](https://github.com/jbaysolutions/vue-grid-layout/tree/vue3-webpack)

> npm i -S https://github.com/fts1025/vue-grid-layout.git#vue3-webpack

**Comment by robertsLando** [comment]
@gmsa Hi Gustavo. I would like to help you with the Vue3 refactor. What's the branch to use? would you consider creating a new repo for that?

**Comment by 50rayn** [comment]
> @gmsa Hi Gustavo. I would like to help you with the Vue3 refactor. What's the branch to use? would you consider creating a new repo for that?
> 

Hello @robertsLando .

I have a Vue3 version. [Noction/vue-draggable-grid](https://github.com/Noction/vue-draggable-grid) is our version. We stopped a little the development due lack of time.

**Comment by robertsLando** [comment]
Hi @50rayn, thanks for the suggestion but I have found this: https://github.com/merfais/vue-grid-layout-v3?rgh-link-date=2025-05-08T10%3A22%3A16Z

And it seems the most maintained and the only working Vue3 version I have found of this library 🙌🏼

**Comment by xmatthias** [comment]
@50rayn yeah, unfortunately this library took unfortunate changes in v1.10 which made everything prior to it incompatible to older versions - with he issue for it (https://github.com/Noction/vue-draggable-grid/issues/60) having been ignored completely by maintainers.
will take a look at this other fork, it looks way more promising than the noction one - which started out great - and then fell off a cliff fast.
